### ISSUE TITLE
兄弟 能教一下怎么配置嘛

### ISSUE THREAD

**Issue by DR34M3R-T** [eenie/YogaDuet-Hackintosh-EFI-OC#2]
实在搞不懂efi分区是什么东西
我用的是黑果小兵的集成包 把ketx、drivers啥的全复制到clover文件夹下了
然后一次内存错误 一次efi分区直接无法引导了
求大佬指点。。。

**Comment by eenie** [comment]
不太清楚你的机型  找对应机型的EFI会好一点
如果你是YogaDuet  可以直接下载我的配置把EFI文件夹复制进去EFI分区就可以了
![22013045-6079-4611-BEDE-A8C5D73E6264](https://user-images.githubusercontent.com/10646956/104260428-75b13800-54be-11eb-8421-bd4527a1ce5a.png)

**Comment by DR34M3R-T** [comment]
设备是yoga duet
目测已经找到问题了
我把你这个oc的下的驱动直接拷到clover里了
而且config.plist没配置
这两天百度了各种教程 说是oc与clover的config.plist不通用
我再试试看
谢谢老哥

**Comment by DR34M3R-T** [comment]
成功引导进入安装程序 但是不知道为啥 跑到剩余14分钟时自动重启了

**Comment by DR34M3R-T** [comment]
xd我中奖了 我的yoga duet是三星的pm991固态 网上说这个硬盘不兼容黑苹果。。。

**Comment by acoffeeworld** [comment]
> xd我中奖了 我的yoga duet是三星的pm991固态 网上说这个硬盘不兼容黑苹果。。。

好吧我也中奖了。抹盘到到一半直接重启

**Comment by DR34M3R-T** [comment]
好啦 我这个issue也close了吧 等以后有机会换块2242的硬盘再回来玩玩
