### ISSUE TITLE
同样的配置duet，但是用U盘启动不成功

### ISSUE THREAD

**Issue by acoffeeworld** [eenie/YogaDuet-Hackintosh-EFI-OC#3]
Q1：RT，一模一样的配置，用在U盘的配置起不来
Q2：这个OC版本是多少呢，如果是063就好了，可以装bigSur

**Comment by eenie** [comment]
等我今晚更新到最新065版本   支持bigsur

**Comment by acoffeeworld** [comment]
用这个引导的时候，找不到U盘上的10.15.6系统。

你现在的部署模式是单硬盘双系统嘛






------------------&nbsp;Original&nbsp;------------------

**Comment by acoffeeworld** [comment]
好吧我也中奖了 我这批是pm991。抹盘到到一半直接重启

**Comment by eenie** [comment]
是的
硬盘分区了  EFI、WIN、MAC三个区
你可以先用黑果小兵的分享的镜像，按照他的教程写到U盘
然后用我的EFI替换掉你写好的U盘上的EFI
PM991好像没啥办法  不太清楚  去远景论坛看看治理pm981的帖子  看看有没有kext可以兼容的

**Comment by acoffeeworld** [comment]
EFI简单，我会配config.plist。上周末跑了下安装 一直安装不进去，原来是pm991惹的祸



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Eenie"<notifications@github.com&gt;; 
发送时间: 2021年1月25日(星期一) 中午11:31
收件人: "eenie/YogaDuet-Hackintosh-EFI-OC"<YogaDuet-Hackintosh-EFI-OC@noreply.github.com&gt;; 
抄送: "咖啡"<2535704039@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [eenie/YogaDuet-Hackintosh-EFI-OC] 同样的配置duet，但是用U盘启动不成功 (#3)





 
是的
 硬盘分区了  EFI、WIN、MAC三个区
 你可以先用黑果小兵的分享的镜像，按照他的教程写到U盘
 然后用我的EFI替换掉你写好的U盘上的EFI
 PM991好像没啥办法  不太清楚  去远景论坛看看治理pm981的帖子  看看有没有kext可以兼容的
 
&mdash;

**Comment by DR34M3R-T** [comment]
孩子哭了。。。如果有弄好了的请踢我一下

**Comment by acoffeeworld** [comment]
> 孩子哭了。。。如果有弄好了的请踢我一下

http://k61.org/e1134a6c.html
已经放弃了，老老实实用win10笔记本，台式继续吃黑苹果，不过这个链接你可以试试，据说打完补丁之后性能跟机械盘一样，我直接自闭
