### ISSUE TITLE
引导时提示找不到EFI/BOOT/grubx64.efi

### ISSUE THREAD

**Issue by Hzbeta** [eenie/YogaDuet-Hackintosh-EFI-OC#5]
这个文件不是引导Linux的吗，在OC配置里面的blessoverride字段也只看到有Windows的efi，没有grubx64，为啥会显示找不到/EFI/BOOT/grubx64.efi？
big sur和catalina都试过了，很困惑

**Comment by BI4LDK** [comment]
在我这的正常

**Comment by DroWez** [comment]
此外，问题不会从闪存驱动器启动安装
